//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuMascota.AccesoDatos.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public long IdMascota { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Color { get; set; }
        public string Raza { get; set; }
        public string Imagen { get; set; }
        public string Estado { get; set; }
        public string Descripcion { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<long> Latitud { get; set; }
        public Nullable<long> Longitud { get; set; }
        public string TipoAnimal { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
